#!/usr/bin/env bash

#
# easily download all images from an imgbox gallery
#

function help {
	local script_name=$0

	printf "\\nUsage: %s imgbox_gallery_url\\n" "${script_name}"
	printf "\\nEasily download all images from an imgbox gallery\\n\\n"
}

function check_requirements {

	declare -a requirements=("curl")

	for requirement in "${requirements[@]}"; do

		if ! command -v "${requirement}" &> /dev/null; then
			printf "\\nError: '%s' is a requirement and wasn't found in this system.\\n\\n" "${requirement}"
			exit 1
		fi

	done
}

function extract_name {
	local url="$1"

	temp=${url##*/}
	echo ${temp%%_*}
}

function number_of_images_in_the_gallery {
	local url="$1"

	curl -s "${url}" | grep -o -E "\\d+ images" | cut -f1 -d" "
}

function is_imgbox_gallery_url {
	local url="$1"

	if [[ "${url}" =~ https?://imgbox.com/g/ ]]; then
		true
	else
		false
	fi
}

check_requirements

if [[ $# -ne 1 ]]; then
	help
	exit 1
fi

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
	help
	exit 0
fi

gallery_url="$1"

if ! is_imgbox_gallery_url "${gallery_url}"; then
	printf "\\nError: The inputed url doesn't appear to be a proper imgbox gallery url\\n\\n"
	exit 1
fi

gallery_name=$(extract_name "${gallery_url}")

mkdir -p "${gallery_name}" && cd "${gallery_name}"

printf "\\n\\nAbout to save %d images to folder %s/\\n\\n" $(number_of_images_in_the_gallery "${gallery_url}") "${gallery_name}"

for url in $(curl -s "${gallery_url}" | grep -E -o 'thumbs\d+.*"' | tr -d '"'); do

	printf -v link "https://imgbox.com/%s" $(extract_name "${url}")
	temp=$(curl -s "${link}" | grep -E -o 'https?.*download=true')

	curl -O -# ${temp%%\?*}
done

printf "\\n\\n%s images were saved to folder %s/\\n\\n" $(find . -type f | wc -l) "${gallery_name}"
